### ISSUE TITLE
Author, I think your MOD should change the way the data is arranged

### ISSUE THREAD

**Issue by mengzhu3261** [MaliciousFiles/BedWarsStats#2]
I just tested the MOD online, it worked very well, but I think there is something wrong with the bw data list, I think it should be level-fkrd-final-wins-wlr. By the way, the mods my friends made for me are basically in this arrangement, I think it is very good, can you change it
![~3N Y`{}XJ$SSA$Y492PWZP](https://github.com/MaliciousFiles/BedWarsStats/assets/147975362/9cbdb877-4bd6-4615-b86d-7f1692f631b1)
![0QCDDSQ$C$B0}5Y~{K`HXEB](https://github.com/MaliciousFiles/BedWarsStats/assets/147975362/c061ac45-256d-45da-857e-d5737371d224)
![Z5X~R 5$H7GKWMY3R `JH9C](https://github.com/MaliciousFiles/BedWarsStats/assets/147975362/a9bae210-18d6-486d-9f74-016bb955235b)
![Z@%I5D `H37)( I1{UIA1OG](https://github.com/MaliciousFiles/BedWarsStats/assets/147975362/ab2d1506-8391-4610-bb67-6a87175e2068)

**Comment by mengzhu3261** [comment]
@MaliciousFiles

**Comment by mengzhu3261** [comment]
![~3N Y`{}XJ$SSA$Y492PWZP](https://github.com/MaliciousFiles/BedWarsStats/assets/147975362/d3e5c161-e4b5-4acc-832c-c54559381029)
good job

**Comment by MaliciousFiles** [comment]
I have it the way it is right now because I believe it is a pretty accurate order of importance for the stats. FKDR is generally the most accurate tell of skill, but I have also found kills to be rather accurate as well. I'm not quite sure if you were asking for something else, but I do not plan to change the order of the stats at this time.

FYI, I had to update my API key, so please re-download the mod.
